import { GetServerSideProps, InferGetServerSidePropsType } from "next";
import Head from "next/head";
import Link from "next/link";
import useSWRImmutable from "swr/immutable";
import styles from "@/styles/Home.module.css";
import { BASE_ROUTES } from "@/const/routes";
import { getAlbums, getUsers } from "@/lib";
import { User } from "@/types/users";

export const getServerSideProps = (async () => {
  const users = await getUsers();
  return {
    props: {
      users,
    },
  };
}) satisfies GetServerSideProps<{ users: User[] }>;

export default function Home({
  users,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  const { data, isLoading } = useSWRImmutable(
    "albums",
    async () => await getAlbums(),
  );
  if (isLoading) return <p>Loading...</p>;
  return (
    <>
      <Head>
        <title>next-cache</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <nav>
          <ul>
            {BASE_ROUTES.map(({ href, label }) => (
              <li key={label}>
                <Link href={href}>{label}</Link>
              </li>
            ))}
          </ul>
        </nav>
        <ul>{data?.map((album) => <li key={album.id}>{album.title}</li>)}</ul>
        <ul>
          {users.map((user) => (
            <li key={user.id}>{user.name}</li>
          ))}
        </ul>
      </main>
    </>
  );
}
