import Head from "next/head";
import Link from "next/link";
import styles from "@/styles/Home.module.css";
import { BASE_ROUTES } from "@/const/routes";

export default function Home() {
  return (
    <>
      <Head>
        <title>next-cache</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <nav>
          <ul>
            {BASE_ROUTES.map(({ href, label }) => (
              <li key={label}>
                <Link href={href}>{label}</Link>
              </li>
            ))}
          </ul>
        </nav>
      </main>
    </>
  );
}
